name: Demo Repo Secret

on:
  workflow_dispatch:    # this gives you the Run workflow button

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print masked secret
        run: echo "My secret is:$test_key"
        env:
          test_key: ${{ secrets.test_key }}
